version: '3.1'
services:
  next-frontend:
    build: ./CommunityFrontend
    ports:
      - "127.0.0.1:10001:3000"
    depends_on:
      - next-backend

  java-backend:
    build: ./JavaBackend
    ports:
      - "127.0.0.1:10002:8080"
    networks:
      - db-network
    env_file:
      - .env

networks:
  db-network:
    external: true
